[app]
  name = "crontab"
  host = "127.0.0.1"
  port = 8080

[mysql]
  host = "127.0.0.1"
  port = 3306
  user = ""
  pass = ""
  dbname = ""
  maxLifeTimeConn = 60
  maxIdleConn = 60
  maxOpenConn = 10